### ISSUE TITLE
Шаги рефакторинга

### ISSUE THREAD

**Issue by NikitaVKalinin** [fanadd/zbitnev-kalinin-arcanoid#1]
- [x] Перенести пакеты ball, paddle, brick в entity.
- [x] Переименовать Behaviour в Reaction.
- [x] Переимновать GameFieldView + Factory в ArkanoidFieldView.
- [x] Удалить старых слушателей из бывшего interaction и перейти к использованию entity.Sprite. update() из EntityView должен исчезнуть.
- [x] Сделать сообщение в ArkanoidFieldView о создаваемых объектах в модели. add/removeEntityView, возможно, следует закрыть: класс сам реагирует на изменения в модели.
  ...
- [x] Разработать CollisionDetector (можно параллельно с другими задачами).
- [x] Перейти к использованию CollisionDetector: избавиться от передачи информации о коллизиях в поле, удалить PublishingCollisionManager, подключить CollisionDetector.
- [x] Перенести границы поля в CollisionDetector.
  ...
- [x] Чистка. Класс DefaultObjectViewFactory, скорее всего, больше не понадобится.

Прочее.
- [x] Сделать Speed2D неизменяемым.

Вопросы.
- Что такое renderDeprecated() в EntityView? Чтобы пометить метод устаревшим, нужно приписать аннотацию @Deprecated.

**Comment by fanadd** [comment]
Замечена любопытная деталь: после удаления пересылки сообщениями игровые объекты замедлились, примерно раза в два. Возможно, то был какой-то побочный эффект дублирующейся информации, который, кстати, и приводил к тому, что у нас oldX, oldY не работали
